export const FONT_OPTIONS = [
  { label: '01. Mặc định (Sans-serif)', value: 'sans-serif' },
  { label: '02. Mặc định (Serif)', value: 'serif' },
  { label: '03. Inter (Hiện đại)', value: '"Inter", sans-serif' },
  { label: '04. Be Vietnam Pro', value: '"Be Vietnam Pro", sans-serif' },
  { label: '05. Montserrat', value: '"Montserrat", sans-serif' },
  { label: '06. Space Grotesk', value: '"Space Grotesk", sans-serif' },
  { label: '07. Playfair Display (Sang trọng)', value: '"Playfair Display", serif' },
  { label: '08. Lora', value: '"Lora", serif' },
  { label: '09. Dancing Script (Thư pháp 1)', value: '"Dancing Script", cursive' },
  { label: '10. Great Vibes (Thư pháp 2)', value: '"Great Vibes", cursive' },
  { label: '11. Pattaya (Việt hóa)', value: '"Pattaya", sans-serif' },
  { label: '12. Sriracha (Viết tay)', value: '"Sriracha", cursive' },
  { label: '13. Charm (Thanh lịch)', value: '"Charm", cursive' },
  { label: '14. Oswald', value: '"Oswald", sans-serif' },
  { label: '15. UVNAiCapNang', value: '"UVNAiCapNang", sans-serif' },
  { label: '16. UVNAiCapNhe', value: '"UVNAiCapNhe", sans-serif' },
  { label: '17. UVNAiCap B', value: '"UVNAiCap B", sans-serif' },
  { label: '18. UVNAiCap R', value: '"UVNAiCap R", sans-serif' },
  { label: '19. UVNAnhHaiNhe I', value: '"UVNAnhHaiNhe I", sans-serif' },
  { label: '20. UVNAnhHaiNhe R', value: '"UVNAnhHaiNhe R", sans-serif' },
  { label: '21. UVNAnhHai B', value: '"UVNAnhHai B", sans-serif' },
  { label: '22. UVNAnhHai BI', value: '"UVNAnhHai BI", sans-serif' },
  { label: '23. UVNAnhHai I', value: '"UVNAnhHai I", sans-serif' },
  { label: '24. UVNAnhHai R', value: '"UVNAnhHai R", sans-serif' },
  { label: '25. UVNAnhSang', value: '"UVNAnhSang", sans-serif' },
  { label: '26. UVNBachDangNang I', value: '"UVNBachDangNang I", sans-serif' },
  { label: '27. UVNBachDangNang R', value: '"UVNBachDangNang R", sans-serif' },
  { label: '28. UVNBachDang B', value: '"UVNBachDang B", sans-serif' },
  { label: '29. UVNBachDang BI', value: '"UVNBachDang BI", sans-serif' },
  { label: '30. UVNBachDang I', value: '"UVNBachDang I", sans-serif' },
  { label: '31. UVNBachDang R', value: '"UVNBachDang R", sans-serif' },
  { label: '32. UVNBachTuyetNang I', value: '"UVNBachTuyetNang I", sans-serif' },
  { label: '33. UVNBachTuyetNang R', value: '"UVNBachTuyetNang R", sans-serif' },
  { label: '34. UVNBachTuyet B', value: '"UVNBachTuyet B", sans-serif' },
  { label: '35. UVNBachTuyet BI', value: '"UVNBachTuyet BI", sans-serif' },
  { label: '36. UVNBachTuyet I', value: '"UVNBachTuyet I", sans-serif' },
  { label: '37. UVNBachTuyet R', value: '"UVNBachTuyet R", sans-serif' },
  { label: '38. UVNBaiHoc B', value: '"UVNBaiHoc B", sans-serif' },
  { label: '39. UVNBaiHoc BI', value: '"UVNBaiHoc BI", sans-serif' },
  { label: '40. UVNBaiHoc I', value: '"UVNBaiHoc I", sans-serif' },
  { label: '41. UVNBaiHoc R', value: '"UVNBaiHoc R", sans-serif' },
  { label: '42. UVNBaiSau B', value: '"UVNBaiSau B", sans-serif' },
  { label: '43. UVNBaiSau N', value: '"UVNBaiSau N", sans-serif' },
  { label: '44. UVNBaiSau Nh', value: '"UVNBaiSau Nh", sans-serif' },
  { label: '45. UVNBaiSau R', value: '"UVNBaiSau R", sans-serif' },
  { label: '46. UVNBaLe', value: '"UVNBaLe", sans-serif' },
  { label: '47. UVNBanhMi', value: '"UVNBanhMi", sans-serif' },
  { label: '48. UVNBanTay', value: '"UVNBanTay", sans-serif' },
  { label: '49. UVNBayBuomHep B', value: '"UVNBayBuomHep B", sans-serif' },
  { label: '50. UVNBayBuomHep N', value: '"UVNBayBuomHep N", sans-serif' },
  { label: '51. UVNBayBuomHep R', value: '"UVNBayBuomHep R", sans-serif' },
  { label: '52. UVNBayBuom B', value: '"UVNBayBuom B", sans-serif' },
  { label: '53. UVNBayBuom N', value: '"UVNBayBuom N", sans-serif' },
  { label: '54. UVNBayBuom R', value: '"UVNBayBuom R", sans-serif' },
  { label: '55. UVNBenXuan B', value: '"UVNBenXuan B", sans-serif' },
  { label: '56. UVNBenXuan R', value: '"UVNBenXuan R", sans-serif' },
  { label: '57. UVNBinhDuong', value: '"UVNBinhDuong", sans-serif' },
  { label: '58. UVNBoQuen', value: '"UVNBoQuen", sans-serif' },
  { label: '59. UVNBucThu', value: '"UVNBucThu", sans-serif' },
  { label: '60. UVNBuiDoi', value: '"UVNBuiDoi", sans-serif' },
  { label: '61. UVNButLong1', value: '"UVNButLong1", sans-serif' },
  { label: '62. UVNButLong2', value: '"UVNButLong2", sans-serif' },
  { label: '63. UVNCatBienNhe I', value: '"UVNCatBienNhe I", sans-serif' },
  { label: '64. UVNCatBienNhe R', value: '"UVNCatBienNhe R", sans-serif' },
  { label: '65. UVNCatBien B', value: '"UVNCatBien B", sans-serif' },
  { label: '66. UVNCatBien BI', value: '"UVNCatBien BI", sans-serif' },
  { label: '67. UVNCatBien I', value: '"UVNCatBien I", sans-serif' },
  { label: '68. UVNCatBien R', value: '"UVNCatBien R", sans-serif' },
  { label: '69. UVNChimBienNang', value: '"UVNChimBienNang", sans-serif' },
  { label: '70. UVNChimBienNhe', value: '"UVNChimBienNhe", sans-serif' },
  { label: '71. UVNChimBien B', value: '"UVNChimBien B", sans-serif' },
  { label: '72. UVNChimBien R', value: '"UVNChimBien R", sans-serif' },
  { label: '73. UVNChinhLuan B', value: '"UVNChinhLuan B", sans-serif' },
  { label: '74. UVNChinhLuan BI', value: '"UVNChinhLuan BI", sans-serif' },
  { label: '75. UVNChinhLuan I', value: '"UVNChinhLuan I", sans-serif' },
  { label: '76. UVNChinhLuan R', value: '"UVNChinhLuan R", sans-serif' },
  { label: '77. UVNCHUKY', value: '"UVNCHUKY", sans-serif' },
  { label: '78. UVNCoDien B', value: '"UVNCoDien B", sans-serif' },
  { label: '79. UVNCoDien R', value: '"UVNCoDien R", sans-serif' },
  { label: '80. UVNConThuy', value: '"UVNConThuy", sans-serif' },
  { label: '81. UVNDaLat B', value: '"UVNDaLat B", sans-serif' },
  { label: '82. UVNDaLat R', value: '"UVNDaLat R", sans-serif' },
  { label: '83. UVNDamCuoi H', value: '"UVNDamCuoi H", sans-serif' },
  { label: '84. UVNDamCuoi R', value: '"UVNDamCuoi R", sans-serif' },
  { label: '85. UVNDinhHon', value: '"UVNDinhHon", sans-serif' },
  { label: '86. UVNDoiMoi', value: '"UVNDoiMoi", sans-serif' },
  { label: '87. UVNDungDan', value: '"UVNDungDan", sans-serif' },
  { label: '88. UVNDzungDakao', value: '"UVNDzungDakao", sans-serif' },
  { label: '89. UVNGiaDinhHep B', value: '"UVNGiaDinhHep B", sans-serif' },
  { label: '90. UVNGiaDinhHep BI', value: '"UVNGiaDinhHep BI", sans-serif' },
  { label: '91. UVNGiaDinhHep I', value: '"UVNGiaDinhHep I", sans-serif' },
  { label: '92. UVNGiaDinhHep R', value: '"UVNGiaDinhHep R", sans-serif' },
  { label: '93. UVNGiaDinh B', value: '"UVNGiaDinh B", sans-serif' },
  { label: '94. UVNGiaDinh BI', value: '"UVNGiaDinh BI", sans-serif' },
  { label: '95. UVNGiaDinh I', value: '"UVNGiaDinh I", sans-serif' },
  { label: '96. UVNGiaDinh R', value: '"UVNGiaDinh R", sans-serif' },
  { label: '97. UVNGiayTrang B', value: '"UVNGiayTrang B", sans-serif' },
  { label: '98. UVNGiayTrang R', value: '"UVNGiayTrang R", sans-serif' },
  { label: '99. UVNGioMayNhe I', value: '"UVNGioMayNhe I", sans-serif' },
  { label: '100. UVNGioMayNhe R', value: '"UVNGioMayNhe R", sans-serif' },
  { label: '101. UVNGioMay B', value: '"UVNGioMay B", sans-serif' },
  { label: '102. UVNGioMay BI', value: '"UVNGioMay BI", sans-serif' },
  { label: '103. UVNGioMay I', value: '"UVNGioMay I", sans-serif' },
  { label: '104. UVNGioMay R', value: '"UVNGioMay R", sans-serif' },
  { label: '105. UVNGiongSong B', value: '"UVNGiongSong B", sans-serif' },
  { label: '106. UVNGiongSong BI', value: '"UVNGiongSong BI", sans-serif' },
  { label: '107. UVNGiongSong I', value: '"UVNGiongSong I", sans-serif' },
  { label: '108. UVNGiongSong R', value: '"UVNGiongSong R", sans-serif' },
  { label: '109. UVNHaiBaTrung', value: '"UVNHaiBaTrung", sans-serif' },
  { label: '110. UVNHaiLong', value: '"UVNHaiLong", sans-serif' },
  { label: '111. UVNHanViet', value: '"UVNHanViet", sans-serif' },
  { label: '112. UVNHoaDao', value: '"UVNHoaDao", sans-serif' },
  { label: '113. UVNHOAKY', value: '"UVNHOAKY", sans-serif' },
  { label: '114. UVNHoaTay1', value: '"UVNHoaTay1", sans-serif' },
  { label: '115. UVNHongHaHep B', value: '"UVNHongHaHep B", sans-serif' },
  { label: '116. UVNHongHaHep BI', value: '"UVNHongHaHep BI", sans-serif' },
  { label: '117. UVNHongHaHep I', value: '"UVNHongHaHep I", sans-serif' },
  { label: '118. UVNHongHaHep R', value: '"UVNHongHaHep R", sans-serif' },
  { label: '119. UVNHongHa B', value: '"UVNHongHa B", sans-serif' },
  { label: '120. UVNHongHa BI', value: '"UVNHongHa BI", sans-serif' },
  { label: '121. UVNHongHa I', value: '"UVNHongHa I", sans-serif' },
  { label: '122. UVNHongHa R', value: '"UVNHongHa R", sans-serif' },
  { label: '123. UVNHuongQue B', value: '"UVNHuongQue B", sans-serif' },
  { label: '124. UVNHuongQue N', value: '"UVNHuongQue N", sans-serif' },
  { label: '125. UVNHuongQue R', value: '"UVNHuongQue R", sans-serif' },
  { label: '126. UVNKeChuyen1', value: '"UVNKeChuyen1", sans-serif' },
  { label: '127. UVNKeChuyen2', value: '"UVNKeChuyen2", sans-serif' },
  { label: '128. UVNKeChuyen3', value: '"UVNKeChuyen3", sans-serif' },
  { label: '129. UVNKieu B', value: '"UVNKieu B", sans-serif' },
  { label: '130. UVNKieu R', value: '"UVNKieu R", sans-serif' },
  { label: '131. UVNKyThuat', value: '"UVNKyThuat", sans-serif' },
  { label: '132. UVNLacLongQuan B', value: '"UVNLacLongQuan B", sans-serif' },
  { label: '133. UVNLacLongQuan R', value: '"UVNLacLongQuan R", sans-serif' },
  { label: '134. UVNLaXanh B', value: '"UVNLaXanh B", sans-serif' },
  { label: '135. UVNLaXanh BI', value: '"UVNLaXanh BI", sans-serif' },
  { label: '136. UVNLaXanh I', value: '"UVNLaXanh I", sans-serif' },
  { label: '137. UVNLaXanh R', value: '"UVNLaXanh R", sans-serif' },
  { label: '138. UVNLYDO ', value: '"UVNLYDO ", sans-serif' },
  { label: '139. UVNMangCauNang I', value: '"UVNMangCauNang I", sans-serif' },
  { label: '140. UVNMangCauNang R', value: '"UVNMangCauNang R", sans-serif' },
  { label: '141. UVNMangCau B', value: '"UVNMangCau B", sans-serif' },
  { label: '142. UVNMangCau BI', value: '"UVNMangCau BI", sans-serif' },
  { label: '143. UVNMangCau I', value: '"UVNMangCau I", sans-serif' },
  { label: '144. UVNMangCau R', value: '"UVNMangCau R", sans-serif' },
  { label: '145. UVNMangTre', value: '"UVNMangTre", sans-serif' },
  { label: '146. UVNMauTim1', value: '"UVNMauTim1", sans-serif' },
  { label: '147. UVNMauTim2', value: '"UVNMauTim2", sans-serif' },
  { label: '148. UVNMayChuP B', value: '"UVNMayChuP B", sans-serif' },
  { label: '149. UVNMayChuP BI', value: '"UVNMayChuP BI", sans-serif' },
  { label: '150. UVNMayChuP I', value: '"UVNMayChuP I", sans-serif' },
  { label: '151. UVNMayChuP R', value: '"UVNMayChuP R", sans-serif' },
  { label: '152. UVNMinhMap', value: '"UVNMinhMap", sans-serif' },
  { label: '153. UVNMoiHong', value: '"UVNMoiHong", sans-serif' },
  { label: '154. UVNMotMoi', value: '"UVNMotMoi", sans-serif' },
  { label: '155. UVNMuaThu', value: '"UVNMuaThu", sans-serif' },
  { label: '156. UVNMucCham', value: '"UVNMucCham", sans-serif' },
  { label: '157. UVNNguyenDu', value: '"UVNNguyenDu", sans-serif' },
  { label: '158. UVNNhanNang I', value: '"UVNNhanNang I", sans-serif' },
  { label: '159. UVNNhanNang R', value: '"UVNNhanNang R", sans-serif' },
  { label: '160. UVNNhan B', value: '"UVNNhan B", sans-serif' },
  { label: '161. UVNNhan BI', value: '"UVNNhan BI", sans-serif' },
  { label: '162. UVNNhan I', value: '"UVNNhan I", sans-serif' },
  { label: '163. UVNNhan R', value: '"UVNNhan R", sans-serif' },
  { label: '164. UVNNhatKy B', value: '"UVNNhatKy B", sans-serif' },
  { label: '165. UVNNhatKy BI', value: '"UVNNhatKy BI", sans-serif' },
  { label: '166. UVNNhatKy I', value: '"UVNNhatKy I", sans-serif' },
  { label: '167. UVNNhatKy R', value: '"UVNNhatKy R", sans-serif' },
  { label: '168. UVNPhuongTay', value: '"UVNPhuongTay", sans-serif' },
  { label: '169. UVNSachVo B', value: '"UVNSachVo B", sans-serif' },
  { label: '170. UVNSachVo BI', value: '"UVNSachVo BI", sans-serif' },
  { label: '171. UVNSachVo I', value: '"UVNSachVo I", sans-serif' },
  { label: '172. UVNSachVo R', value: '"UVNSachVo R", sans-serif' },
  { label: '173. UVNSaigon B', value: '"UVNSaigon B", sans-serif' },
  { label: '174. UVNSaigon BI', value: '"UVNSaigon BI", sans-serif' },
  { label: '175. UVNSaigon I', value: '"UVNSaigon I", sans-serif' },
  { label: '176. UVNSaigon R', value: '"UVNSaigon R", sans-serif' },
  { label: '177. UVNSangSong B', value: '"UVNSangSong B", sans-serif' },
  { label: '178. UVNSangSong N', value: '"UVNSangSong N", sans-serif' },
  { label: '179. UVNSangSong R', value: '"UVNSangSong R", sans-serif' },
  { label: '180. UVNThangGieng I', value: '"UVNThangGieng I", sans-serif' },
  { label: '181. UVNThangGieng R', value: '"UVNThangGieng R", sans-serif' },
  { label: '182. UVNThangVu', value: '"UVNThangVu", sans-serif' },
  { label: '183. UVNThanhBinh', value: '"UVNThanhBinh", sans-serif' },
  { label: '184. UVNThanhPhoNang', value: '"UVNThanhPhoNang", sans-serif' },
  { label: '185. UVNThanhPho B', value: '"UVNThanhPho B", sans-serif' },
  { label: '186. UVNThanhPho R', value: '"UVNThanhPho R", sans-serif' },
  { label: '187. UVNThayGiaoNang I', value: '"UVNThayGiaoNang I", sans-serif' },
  { label: '188. UVNThayGiaoNang R', value: '"UVNThayGiaoNang R", sans-serif' },
  { label: '189. UVNThayGiaoNhe I', value: '"UVNThayGiaoNhe I", sans-serif' },
  { label: '190. UVNThayGiaoNhe R', value: '"UVNThayGiaoNhe R", sans-serif' },
  { label: '191. UVNThayGiao B', value: '"UVNThayGiao B", sans-serif' },
  { label: '192. UVNThayGiao BI', value: '"UVNThayGiao BI", sans-serif' },
  { label: '193. UVNThayGiao I', value: '"UVNThayGiao I", sans-serif' },
  { label: '194. UVNThayGiao R', value: '"UVNThayGiao R", sans-serif' },
  { label: '195. UVNThoiDai1', value: '"UVNThoiDai1", sans-serif' },
  { label: '196. UVNThoiDai2', value: '"UVNThoiDai2", sans-serif' },
  { label: '197. UVNThoiNayNang I', value: '"UVNThoiNayNang I", sans-serif' },
  { label: '198. UVNThoiNayNang R', value: '"UVNThoiNayNang R", sans-serif' },
  { label: '199. UVNThoiNay B', value: '"UVNThoiNay B", sans-serif' },
  { label: '200. UVNThoiNay BI', value: '"UVNThoiNay BI", sans-serif' },
  { label: '201. UVNThoiNay I', value: '"UVNThoiNay I", sans-serif' },
  { label: '202. UVNThoiNay R', value: '"UVNThoiNay R", sans-serif' },
  { label: '203. UVNThuTu', value: '"UVNThuTu", sans-serif' },
  { label: '204. UVNTinTucHepThem B', value: '"UVNTinTucHepThem B", sans-serif' },
  { label: '205. UVNTinTucHepThem R', value: '"UVNTinTucHepThem R", sans-serif' },
  { label: '206. UVNTinTucHep B', value: '"UVNTinTucHep B", sans-serif' },
  { label: '207. UVNTinTucHep BI', value: '"UVNTinTucHep BI", sans-serif' },
  { label: '208. UVNTinTucHep I', value: '"UVNTinTucHep I", sans-serif' },
  { label: '209. UVNTinTucHep R', value: '"UVNTinTucHep R", sans-serif' },
  { label: '210. UVNTinTucNhe I', value: '"UVNTinTucNhe I", sans-serif' },
  { label: '211. UVNTinTucNhe R', value: '"UVNTinTucNhe R", sans-serif' },
  { label: '212. UVNTinTuc B', value: '"UVNTinTuc B", sans-serif' },
  { label: '213. UVNTinTuc BI', value: '"UVNTinTuc BI", sans-serif' },
  { label: '214. UVNTinTuc I', value: '"UVNTinTuc I", sans-serif' },
  { label: '215. UVNTinTuc R', value: '"UVNTinTuc R", sans-serif' },
  { label: '216. UVNVanChuongNang R', value: '"UVNVanChuongNang R", sans-serif' },
  { label: '217. UVNVanChuong B', value: '"UVNVanChuong B", sans-serif' },
  { label: '218. UVNVanChuong I', value: '"UVNVanChuong I", sans-serif' },
  { label: '219. UVNVanChuong R', value: '"UVNVanChuong R", sans-serif' },
  { label: '220. UVNVan B', value: '"UVNVan B", sans-serif' },
  { label: '221. UVNVan R', value: '"UVNVan R", sans-serif' },
  { label: '222. UVNVienDu', value: '"UVNVienDu", sans-serif' },
  { label: '223. UVNVietSach B', value: '"UVNVietSach B", sans-serif' },
  { label: '224. UVNVietSach BI', value: '"UVNVietSach BI", sans-serif' },
  { label: '225. UVNVietSach I', value: '"UVNVietSach I", sans-serif' },
  { label: '226. UVNVietSach R', value: '"UVNVietSach R", sans-serif' },
  { label: '227. UVNViVi', value: '"UVNViVi", sans-serif' },
  { label: '228. UVNVungTau', value: '"UVNVungTau", sans-serif' }
];
