export const FONT_OPTIONS = [
  { label: '01. Mặc định (Sans-serif)', value: 'sans-serif' },
  { label: '02. Mặc định (Serif)', value: 'serif' },
  { label: '03. Inter (Hiện đại)', value: '"Inter", sans-serif' },
  { label: '04. Be Vietnam Pro', value: '"Be Vietnam Pro", sans-serif' },
  { label: '05. Montserrat', value: '"Montserrat", sans-serif' },
  { label: '06. Space Grotesk', value: '"Space Grotesk", sans-serif' },
  { label: '07. Playfair Display (Sang trọng)', value: '"Playfair Display", serif' },
  { label: '08. Lora', value: '"Lora", serif' },
  { label: '09. Dancing Script (Thư pháp 1)', value: '"Dancing Script", cursive' },
  { label: '10. Great Vibes (Thư pháp 2)', value: '"Great Vibes", cursive' },
  { label: '11. Pattaya (Việt hóa)', value: '"Pattaya", sans-serif' },
  { label: '12. Sriracha (Viết tay)', value: '"Sriracha", cursive' },
  { label: '13. Charm (Thanh lịch)', value: '"Charm", cursive' },
  { label: '14. Oswald', value: '"Oswald", sans-serif' },
  { label: '15. FC Chomp', value: '"FC Chomp", sans-serif' },
  { label: '16. FC Coldwell Bridges', value: '"FC Coldwell Bridges", sans-serif' },
  { label: '17. FC Daytonica', value: '"FC Daytonica", sans-serif' },
  { label: '18. FC Mikado Medium', value: '"FC Mikado Medium", sans-serif' },
  { label: '19. HN Kaldista Project', value: '"HN Kaldista Project", sans-serif' },
  { label: '20. MTD Yolanda Princess', value: '"MTD Yolanda Princess", sans-serif' },
  { label: '21. SFU Franklin Gothic Book', value: '"SFU Franklin Gothic Book", sans-serif' },
  { label: '22. SFU Franklin Gothic Book Oblique', value: '"SFU Franklin Gothic Book Oblique", sans-serif' },
  { label: '23. SFU Franklin Gothic Demi', value: '"SFU Franklin Gothic Demi", sans-serif' },
  { label: '24. SFU Franklin Gothic Demi Oblique', value: '"SFU Franklin Gothic Demi Oblique", sans-serif' },
  { label: '25. SFU Franklin Gothic Heavy', value: '"SFU Franklin Gothic Heavy", sans-serif' },
  { label: '26. SVN Hottroof Semhesta', value: '"SVN Hottroof Semhesta", sans-serif' },
  { label: '27. TQ Kingston', value: '"TQ Kingston", sans-serif' },
  { label: '28. UTM Yves KT', value: '"UTM Yves KT", sans-serif' },
  { label: '29. UTM Yves KT Bold', value: '"UTM Yves KT Bold", sans-serif' },
  { label: '30. UTM Yves KT Bold Italic', value: '"UTM Yves KT Bold Italic", sans-serif' },
  { label: '31. UTM Azkia', value: '"UTM Azkia", sans-serif' },
  { label: '32. UTM Candlescript Pro', value: '"UTM Candlescript Pro", sans-serif' },
  { label: '33. UVN Ky Thuat', value: '"UVN Ky Thuat", sans-serif' },
  { label: '34. UVN Thang Vu', value: '"UVN Thang Vu", sans-serif' },
  { label: '35. UVN Thoi Dai 2', value: '"UVN Thoi Dai 2", sans-serif' },
  { label: '36. VNF Shelia Regular', value: '"VNF Shelia Regular", sans-serif' }
];
