export const FONT_OPTIONS = [
  { label: 'Mặc định (Sans-serif)', value: 'sans-serif' },
  { label: 'Mặc định (Serif)', value: 'serif' },
  { label: 'Inter (Hiện đại)', value: '"Inter", sans-serif' },
  { label: 'Be Vietnam Pro', value: '"Be Vietnam Pro", sans-serif' },
  { label: 'Montserrat', value: '"Montserrat", sans-serif' },
  { label: 'Space Grotesk', value: '"Space Grotesk", sans-serif' },
  { label: 'Playfair Display (Sang trọng)', value: '"Playfair Display", serif' },
  { label: 'Lora', value: '"Lora", serif' },
  { label: 'Dancing Script (Thư pháp 1)', value: '"Dancing Script", cursive' },
  { label: 'Great Vibes (Thư pháp 2)', value: '"Great Vibes", cursive' },
  { label: 'Pattaya (Việt hóa)', value: '"Pattaya", sans-serif' },
  { label: 'Sriracha (Viết tay)', value: '"Sriracha", cursive' },
  { label: 'Charm (Thanh lịch)', value: '"Charm", cursive' },
  { label: 'Oswald', value: '"Oswald", sans-serif' },
  { label: 'FC Chomp', value: '"FC Chomp", sans-serif' },
  { label: 'FC Coldwell Bridges', value: '"FC Coldwell Bridges", sans-serif' },
  { label: 'FC Daytonica', value: '"FC Daytonica", sans-serif' },
  { label: 'FC Mikado Medium', value: '"FC Mikado Medium", sans-serif' },
  { label: 'HN Kaldista Project', value: '"HN Kaldista Project", sans-serif' },
  { label: 'MTD Yolanda Princess', value: '"MTD Yolanda Princess", sans-serif' },
  { label: 'SFU Franklin Gothic Book', value: '"SFU Franklin Gothic Book", sans-serif' },
  { label: 'SFU Franklin Gothic Book Oblique', value: '"SFU Franklin Gothic Book Oblique", sans-serif' },
  { label: 'SFU Franklin Gothic Demi', value: '"SFU Franklin Gothic Demi", sans-serif' },
  { label: 'SFU Franklin Gothic Demi Oblique', value: '"SFU Franklin Gothic Demi Oblique", sans-serif' },
  { label: 'SFU Franklin Gothic Heavy', value: '"SFU Franklin Gothic Heavy", sans-serif' },
  { label: 'SVN Hottroof Semhesta', value: '"SVN Hottroof Semhesta", sans-serif' },
  { label: 'TQ Kingston', value: '"TQ Kingston", sans-serif' },
  { label: 'UTM Yves KT', value: '"UTM Yves KT", sans-serif' },
  { label: 'UTM Yves KT Bold', value: '"UTM Yves KT Bold", sans-serif' },
  { label: 'UTM Yves KT Bold Italic', value: '"UTM Yves KT Bold Italic", sans-serif' },
  { label: 'UTM Azkia', value: '"UTM Azkia", sans-serif' },
  { label: 'UTM Candlescript Pro', value: '"UTM Candlescript Pro", sans-serif' },
  { label: 'UVN Ky Thuat', value: '"UVN Ky Thuat", sans-serif' },
  { label: 'UVN Thang Vu', value: '"UVN Thang Vu", sans-serif' },
  { label: 'UVN Thoi Dai 2', value: '"UVN Thoi Dai 2", sans-serif' },
  { label: 'VNF Shelia Regular', value: '"VNF Shelia Regular", sans-serif' }
];
